// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAddr = "address"

// Addr mapped from table <address>
type Addr struct {
	ID      int32  `gorm:"column:id;type:int(11);primaryKey" json:"id" newTag:"tag info"` // id
	Address string `gorm:"column:address;type:varchar(255)" json:"address"`               // address
	Name    string `gorm:"column:name;type:varchar(255)" json:"name"`                     // name
	Tag     string `gorm:"column:tag;type:varchar(255)" json:"tag"`                       // address tag
	UserID  int32  `gorm:"column:user_id;type:int(11)" json:"user_id"`                    // userID
}

// TableName Addr's table name
func (*Addr) TableName() string {
	return TableNameAddr
}
