// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNamePerson = "people"

// Person mapped from table <people>
type Person struct {
	ID       int32     `gorm:"column:id;type:int(11);primaryKey" json:"id"`
	Name     string    `gorm:"column:name;type:varchar(255)" json:"name"` // user name
	Age      int32     `gorm:"column:age;type:int(11)" json:"age"`
	High     int32     `gorm:"column:high;type:int(255)" json:"high"`
	Birthday time.Time `gorm:"column:birthday;type:datetime" json:"birthday"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
